# Linhas começadas com '#' são comentários
#
# Target 'hello', depende de 'hello.c', e
# basta rodar `gcc -o hello hello.c` para
# construí-lo
# Note que chamando o make duas vezes
# seguidas sem alterar o .c ele só rola os
# gcc uma vez =]
hello : hello.c
	gcc -o hello hello.c
